### ISSUE TITLE
how does this repo compare to drivendata/cookiecutter-data-science ?

### ISSUE THREAD

**Issue by shadiakiki1986** [FutureFacts/generator-data-science#3]
Hello
This repository seems similar to 
https://github.com/drivendata/cookiecutter-data-science

How is this repo different?

**Comment by FlorisHoogenboom** [comment]
It is indeed very similar. However, this repository uses Yeoman in the background and not the Cookiecutter scafolding tool. Also, this automatically sets up an Anaconda environment for you to work in, something the cookiecutter-ds project does not do. Lastly, my goal would be to add R-support as well (see #1).
